name: deploy-gena11yhelper

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t gena11yhelper:latest ./app

      - name: Push to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: |
          docker tag gena11yhelper:latest ${{ secrets.DOCKER_USER }}/gena11yhelper:latest
          docker push ${{ secrets.DOCKER_USER }}/gena11yhelper:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH environment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          
          ssh-keyscan ${{ secrets.AWS_EC2_IP }} > ~/.ssh/known_hosts 2>/dev/null
          
          ssh -i ~/.ssh/deploy-key.pem -o StrictHostKeyChecking=yes ubuntu@${{ secrets.AWS_EC2_IP }} "echo 'SSH connection successful!'"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: fetch terraform outputs
        id: terraform
        run: |
          cd terraform
          terraform init
          echo "bucket_name=$(terraform output -raw s3_bucket_name)" >> $GITHUB_OUTPUT
          echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      - name: Verify EC2 accessibility
        run: |
          ssh -i ~/.ssh/deploy-key.pem ubuntu@${{ steps.terraform.outputs.public_ip }} \
            "docker --version && echo 'EC2 ready for deployment'"

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/deploy-key.pem ubuntu@${{ steps.terraform.outputs.public_ip }} \
          "docker stop gena11y || true; \
           docker rm gena11y || true; \
           docker pull ${{ secrets.DOCKER_USER }}/gena11yhelper:latest; \
           docker run -d \
             --name gena11y \
             --restart unless-stopped \
             -p 8501:8501 \
             -e OPENAI_API_KEY='${{ secrets.OPENAI_KEY }}' \
             -e WANDB_API_KEY='${{ secrets.WANDB_KEY }}' \
             -e PROMPT_BUCKET='${{ steps.terraform.outputs.bucket_name }}' \
             ${{ secrets.DOCKER_USER }}/gena11yhelper:latest"
        
      - name: Verify deployment
        run: |
          sleep 10
          curl -s http://${{ steps.terraform.outputs.public_ip }}:8501 | grep -q "GenA11yHelper" \
            && echo "Deployment successful" \
            || (echo "Deployment verification failed" && exit 1)