name: promote-best-prompt  
on:  
  schedule:  
    - cron: "0 0 * * 0"  # TODO settle on a time
  workflow_dispatch:      # manual trigger   

jobs:  
  evaluate-and-promote:  
    runs-on: ubuntu-latest  
    steps:  
      - name: checkout  
        uses: actions/checkout@v4  

      - name: AWS CLI config 
        uses: aws-actions/configure-aws-credentials@v4  
        with:  
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          aws-region: us-east-1  

      - name: py setup  
        uses: actions/setup-python@v5  
        with:  
          python-version: "3.10"  

      - name: install dependencies  
        run: |  
          pip install wandb boto3 pandas numpy  

      - name: fetch metrics & determine best prompt
        env:  
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}  
        run: |  
          python scripts/evaluate_prompts.py  

      - name: update prod prompt in S3 bucket
        run: |  
          aws s3 cp winning_prompt.txt s3://gena11yhelper-prompts/production.txt
          echo "New prod prompt: $(cat winning_prompt.txt)"  

      - name: Notify team  
        uses: actions/github-script@v7  
        with:  
          script: |  
            github.rest.issues.createComment({  
              issue_number: context.issue.number,  
              owner: context.repo.owner,  
              repo: context.repo.repo,  
              body: "New prod prompt deployed: `$(cat winning_prompt.txt)`"  
            })  